// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"JettyPayGo/internal/biz"
	"JettyPayGo/internal/data"
	"JettyPayGo/internal/service"
	"github.com/go-redis/redis/v8"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitApp(gormDB *gorm.DB, redisDB *redis.Client) *App {
	dataData := data.ProvideData(gormDB, redisDB)
	bizBiz := biz.ProvideBiz(dataData)
	serviceService := service.ProvideService(bizBiz)
	app := ProvideApp(serviceService)
	return app
}
